ci: drop

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,103 +14,6 @@ defaults:
     shell: bash
 
 jobs:
-  clippy:
-    name: Clippy
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          components: clippy
-      - name: Clippy
-        run: cargo xtask clippy
-  
-  fmt:
-    name: Format
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@nightly
-        with:
-          components: rustfmt
-      - name: Check Formatting
-        run: cargo fmt -- --check
-
-  run:
-    name: Run
-    strategy:
-      matrix:
-        target: [x86_64, aarch64, riscv64]
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        include:
-          - target: x86_64
-            os: ubuntu-latest
-            flags: --accel --sudo
-    runs-on: ${{ matrix.os }}
-    steps:
-      - name: Install QEMU (ubuntu)
-        if: matrix.os == 'ubuntu-latest'
-        run: |
-          sudo apt-get update
-          sudo apt-get install qemu-system-x86 qemu-system-arm qemu-system-misc
-      - name: Install QEMU (macos)
-        if: matrix.os == 'macos-latest'
-        run: |
-          brew update
-          brew install qemu
-      - name: Install QEMU (windows)
-        if: matrix.os == 'windows-latest'
-        run: |
-          choco install qemu
-          echo "C:\Program Files\qemu" >> $GITHUB_PATH
-      - uses: actions/checkout@v4
-        with:
-            lfs: true
-      - name: Install stable Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-      - name: Dowload OpenSBI
-        if: matrix.target == 'riscv64'
-        run: |
-          gh release download v1.5.1 --repo riscv-software-src/opensbi --pattern 'opensbi-*-rv-bin.tar.xz'
-          tar -xvf opensbi-*-rv-bin.tar.xz opensbi-1.5.1-rv-bin/share/opensbi/lp64/generic/firmware/fw_jump.bin
-      - name: Download OVMF (prebuilt)
-        run: |
-          gh release download edk2-stable202408-r1 --repo rust-osdev/ovmf-prebuilt --pattern 'edk2-stable*-bin.tar.xz'
-          tar -xvf edk2-stable*-bin.tar.xz edk2-stable202408-r1-bin/x64
-        if: matrix.os != 'ubuntu-latest'
-      - name: Download OVMF (ubuntu)
-        run: |
-          sudo apt-get update
-          sudo apt-get install ovmf
-          mkdir -p edk2-stable202408-r1-bin/x64
-          cp /usr/share/OVMF/OVMF_CODE.fd edk2-stable202408-r1-bin/x64/code.fd
-          cp /usr/share/OVMF/OVMF_VARS.fd edk2-stable202408-r1-bin/x64/vars.fd
-        if: matrix.os == 'ubuntu-latest'
-      - name: Run VM (hello_world, dev)
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }}
-      - name: Run VM (hello_world, release)
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }} --release
-      - name: Run VM (hello_world, uefi, dev)
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }}-uefi
-        if: matrix.target == 'x86_64'
-      - name: Run VM (hello_world, uefi, release)
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }}-uefi --release
-        if: matrix.target == 'x86_64'
-      - name: Run VM (hello_world-microvm, dev)
-        if: matrix.target == 'x86_64' && matrix.os == 'ubuntu-latest'
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }} --microvm
-      - name: Run VM (hello_world-microvm, release)
-        if: matrix.target == 'x86_64' && matrix.os == 'ubuntu-latest'
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }} --microvm --release
-      - name: Run VM (hello_c, dev)
-        if: matrix.target == 'x86_64'
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }} --image hello_c
-      - name: Run VM (hello_c, release)
-        if: matrix.target == 'x86_64'
-        run: cargo xtask ci qemu ${{ matrix.flags }} --target ${{ matrix.target }} --image hello_c --release
-
   run-kvm:
     name: Run (KVM)
     runs-on: ubuntu-24.04
@@ -118,10 +21,15 @@ jobs:
       - name: Install QEMU
         run: |
           sudo apt-get update
-          sudo apt-get install qemu-system-x86
+          sudo apt-get install qemu-system-x86 cpu-checker --no-install-recommends
       - uses: actions/checkout@v4
         with:
             lfs: true
+      - run: kvm-ok
+      # - run: grep -cw vmx /proc/cpuinfo
+      - run: sudo setfacl -m u:${USER}:rw /dev/kvm
+      - run: |
+          [ -r /dev/kvm ] && [ -w /dev/kvm ] && echo "OK" || echo "FAIL"
       - run: git lfs pull
       - run: git lfs checkout
       - name: Install firecracker
@@ -143,18 +51,18 @@ jobs:
           gh release download edk2-stable202408-r1 --repo rust-osdev/ovmf-prebuilt --pattern 'edk2-stable*-bin.tar.xz'
           tar -xvf edk2-stable*-bin.tar.xz edk2-stable202408-r1-bin/x64
       - uses: dtolnay/rust-toolchain@stable
-      - name: Run QEMU (hello_world, dev)
-        run: cargo xtask ci qemu --target x86_64 --accel --sudo
-      - name: Run QEMU (hello_world, release)
-        run: cargo xtask ci qemu --target x86_64 --accel --sudo --release
-      - name: Run QEMU (hello_world-microvm, dev)
-        run: cargo xtask ci qemu --target x86_64 --accel --microvm --sudo
-      - name: Run QEMU (hello_world-microvm, release)
-        run: cargo xtask ci qemu --target x86_64 --accel --microvm --sudo --release
-      - name: Run UEFI (dev)
-        run: cargo xtask ci qemu --target x86_64-uefi --accel --sudo
-      - name: Run UEFI (release)
-        run: cargo xtask ci qemu --target x86_64-uefi --accel --sudo --release
+      # - name: Run QEMU (hello_world, dev)
+      #   run: cargo xtask ci qemu --target x86_64 --accel --sudo
+      # - name: Run QEMU (hello_world, release)
+      #   run: cargo xtask ci qemu --target x86_64 --accel --sudo --release
+      # - name: Run QEMU (hello_world-microvm, dev)
+      #   run: cargo xtask ci qemu --target x86_64 --accel --microvm --sudo
+      # - name: Run QEMU (hello_world-microvm, release)
+      #   run: cargo xtask ci qemu --target x86_64 --accel --microvm --sudo --release
+      # - name: Run UEFI (dev)
+      #   run: cargo xtask ci qemu --target x86_64-uefi --accel --sudo
+      # - name: Run UEFI (release)
+      #   run: cargo xtask ci qemu --target x86_64-uefi --accel --sudo --release
       - name: Run Firecracker (hello_world, dev)
         run: FIRECRACKER=$HOME/.local/bin/firecracker cargo xtask ci firecracker --target x86_64-fc --sudo
       - name: Run Firecracker (hello_world, release)
